/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/current/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invites someone by email. Only an Owner can invite another Owner. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvitationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Joins the tenant with the token from the invitation email. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInvitationRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stations the signed-in user can broadcast to, in every tenant. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyStationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{id}/broadcast-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest URLs, username and a new password for this desktop device; replaces the device's previous one. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BroadcastTargetResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version of the running API. */
        get: operations["GetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/antiforgery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sets the XSRF-TOKEN cookie; echo its value in X-XSRF-TOKEN on unsafe requests made with the session cookie. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an account and sends a confirmation email. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirms the email address with the code from the email. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmEmailRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sends the confirmation email again. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs the SPA in with the session cookie. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emails a password reset link. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sets a new password and signs out every desktop device. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs a desktop device in: access and refresh token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchanges a refresh token for a new pair; the old one stops working. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs the device out and revokes the broadcast credentials it got for itself. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the cookie session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Changes the password and signs out every desktop device. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account and its tenants. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signed-in desktop devices. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Signs one desktop device out and revokes the broadcast credentials it got for itself. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a desktop sign-in: a secret device code to poll with and a short user code to show. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceCodeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceCodeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Polls a desktop sign-in; returns the device's tokens once the user approved it. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/{userCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A pending desktop sign-in, to confirm before approving it. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceRequestResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs the device with this code in to the signed-in account. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCodeRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refuses the desktop sign-in with this code. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCodeRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a tenant on the Free plan; the caller becomes its Owner. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTenantCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Version of the resource; send it back as If-Match to change it. */
                        ETag?: string;
                        /** @description Address of the created resource. */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current tenant (X-Tenant-Id), its plan and usage. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Version of the resource; send it back as If-Match to change it. */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Renames the current tenant. Needs If-Match. */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description The ETag from your last read. Missing: 428; stale: 412. */
                    "If-Match": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTenantCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Version of the resource; send it back as If-Match to change it. */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Precondition Failed */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Precondition Required */
                428: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/tenants/current/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members of the current tenant. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/current/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a member. Only an Owner removes an Owner; the last Owner stays. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stations of the current tenant, newest first. */
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedListOfStationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a station within the plan's station limit and assigns it a stream. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStationCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Version of the resource; send it back as If-Match to change it. */
                        ETag?: string;
                        /** @description Address of the created resource. */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One station; the ETag header is needed to change it. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Version of the resource; send it back as If-Match to change it. */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StationResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Deletes the station; its history is kept and its public ID is never reused. */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @description The ETag from your last read. Missing: 428; stale: 412. */
                    "If-Match"?: string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Precondition Failed */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Changes station settings. Needs If-Match. */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description The ETag from your last read. Missing: 428; stale: 412. */
                    "If-Match": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStationCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Version of the resource; send it back as If-Match to change it. */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Precondition Failed */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Precondition Required */
                428: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/stations/{stationId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credentials of the station's devices, active first. Secrets are never listed. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CredentialResponse"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Issues a credential for one device and shows its secret once. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCredentialCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssuedCredentialResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{stationId}/credentials/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revokes one device's credential. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stationId: string;
                    credentialId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/streaming-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station limits applied to each streaming node, with failures. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamingNodeResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/streaming-nodes/{node}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retries applying station limits now. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    node: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationRequest: {
            token: string;
        };
        /**
         * @description A stream format, as in the mount `/stations/{id}/live.{mp3,opus}`.
         * @enum {unknown}
         */
        AudioFormat: "Mp3" | "Opus";
        /** @description One stream to publish. */
        BroadcastOutput: {
            /** @description Stream format. */
            format: components["schemas"]["AudioFormat"];
            /** @description Send it as the source's `Content-Type`. */
            contentType: string;
            /**
             * Format: uri
             * @description Where to publish (HTTP PUT, Icecast source protocol, TLS).
             */
            ingestUrl: string;
            /**
             * Format: uri
             * @description Where listeners play it.
             */
            listenerUrl: string;
        };
        /**
         * @description Everything the desktop app needs to go live on a station. Contract version 1 (docs/desktop-api.md); it never
         *     contains node, admin or relay credentials.
         */
        BroadcastTargetResponse: {
            /**
             * Format: uuid
             * @description Station ID in the API.
             */
            stationId: string;
            /** @description Station ID in mounts and listener URLs. */
            publicId: string;
            /** @description Station name, e.g. for the `Ice-Name` header. */
            stationName: string;
            /**
             * Format: uuid
             * @description The device's broadcast credential, listed under the station's credentials.
             */
            credentialId: string;
            /** @description Source username: the station's public ID. */
            username: string;
            /** @description Source password of this device. Shown only here: store it now. Asking again replaces it. */
            password: string;
            /**
             * Format: int32
             * @description Highest bitrate the plan accepts, per stream.
             */
            maxBitrateKbps: number | string;
            /** @description Streams the plan allows, MP3 first. */
            outputs: components["schemas"]["BroadcastOutput"][];
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ConfirmEmailRequest: {
            /** Format: uuid */
            userId: string;
            code: string;
        };
        /**
         * @description Issues a broadcast credential for one device of a station.
         * @example {
         *       "deviceLabel": "Studio PC"
         *     }
         */
        CreateCredentialCommand: {
            /** @description Names the device, e.g. "Studio PC"; unique among the station's active credentials. */
            deviceLabel: string;
        };
        /**
         * @description Creates a station in the current tenant.
         * @example {
         *       "name": "Radio Mada",
         *       "slug": "radio-mada",
         *       "description": "News and salegy from Antananarivo",
         *       "genre": "Talk",
         *       "country": "MG",
         *       "language": "mg",
         *       "website": "https://radiomada.example",
         *       "listInDirectory": true
         *     }
         */
        CreateStationCommand: {
            /** @description Display name, e.g. "Radio Mada". */
            name: string;
            /** @description URL name, unique in the tenant, e.g. "radio-mada". */
            slug: string;
            /** @description Shown on the public page and in directories. */
            description?: null | string;
            /** @description e.g. "Talk" or "Salegy". */
            genre?: null | string;
            /** @description ISO 3166-1 alpha-2, e.g. "MG". */
            country?: null | string;
            /** @description BCP 47 tag, e.g. "mg" or "fr". */
            language?: null | string;
            /**
             * Format: uri
             * @description HTTPS address of a square logo.
             */
            logoUrl?: null | string;
            /**
             * Format: uri
             * @description The station's website.
             */
            website?: null | string;
            /**
             * @description List on RadioBrowser, if the plan includes it.
             * @default false
             */
            listInDirectory: boolean;
        };
        /**
         * @description Creates a tenant; the caller becomes its Owner.
         * @example {
         *       "name": "Radio Mada Group",
         *       "slug": "radio-mada"
         *     }
         */
        CreateTenantCommand: {
            /** @description Display name, e.g. "Radio Mada Group". */
            name: string;
            /** @description URL name, unique across Tropicast, e.g. "radio-mada". */
            slug: string;
        };
        /** @description A broadcast credential, without its secret. */
        CredentialResponse: {
            /**
             * Format: uuid
             * @description Credential ID.
             */
            id: string;
            /** @description The device it was issued for. */
            deviceLabel: string;
            /**
             * Format: date-time
             * @description When it was issued.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last accepted connection from Icecast; null if never used.
             */
            lastUsedAt: null | string;
            /**
             * Format: date-time
             * @description When it was revoked; null while active.
             */
            revokedAt: null | string;
        };
        DeviceCodeRequest: {
            deviceName: string;
        };
        /** @description A started desktop sign-in. Show string DeviceCodeResponse.UserCode and Uri DeviceCodeResponse.VerificationUri, then poll. */
        DeviceCodeResponse: {
            /** @description Secret: send it to `/auth/device/token` only. Never show it. */
            deviceCode: string;
            /** @description Short code the user types on the web page, e.g. `BCDF-GHJK`. */
            userCode: string;
            /**
             * Format: uri
             * @description Web page where the user enters the code.
             */
            verificationUri: string;
            /**
             * Format: uri
             * @description The same page with the code filled in, e.g. for a button or a QR code.
             */
            verificationUriComplete: string;
            /**
             * Format: int64
             * @description Seconds until the codes expire.
             */
            expiresIn: number | string;
            /**
             * Format: int64
             * @description Minimum seconds between two polls.
             */
            interval: number | string;
        };
        /** @description A pending desktop sign-in, shown to the user before they approve it. */
        DeviceRequestResponse: {
            /** @description The code, as the device shows it. */
            userCode: string;
            /** @description Name the device gave itself; it becomes the device's name in the account. */
            deviceName: string;
            /**
             * Format: date-time
             * @description When the device asked.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the request expires.
             */
            expiresAt: string;
        };
        DeviceResponse: {
            /** Format: uuid */
            id: string;
            deviceName: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
            current: boolean;
        };
        DeviceTokenRequest: {
            deviceCode: string;
        };
        EmailRequest: {
            email: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        InvitationResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            role: components["schemas"]["MembershipRole"];
            /** Format: date-time */
            expiresAt: string;
        };
        /**
         * @example {
         *       "email": "dj@example.com",
         *       "role": "Broadcaster"
         *     }
         */
        InviteRequest: {
            /** @description Address to invite; the invitee accepts after signing in with it. */
            email: string;
            role: null | components["schemas"]["MembershipRole"];
        };
        /** @description A new credential with its secret. This response is the only time the secret is shown. */
        IssuedCredentialResponse: {
            /** @description The stored credential. */
            credential: components["schemas"]["CredentialResponse"];
            /** @description Icecast source username: the station's public ID. */
            username: string;
            /** @description Icecast source password. Store it in the device now; it cannot be shown again. */
            secret: string;
        };
        /** @description Listener URLs of a station. Uri? ListenerUrls.Opus is null when the plan has no Opus. */
        ListenerUrls: {
            /**
             * Format: uri
             * @description MP3 stream, playable everywhere.
             */
            mp3: string;
            /**
             * Format: uri
             * @description Ogg Opus stream: about half the mobile data of MP3.
             */
            opus: null | string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description A member of the current tenant. */
        MemberResponse: {
            /**
             * Format: uuid
             * @description The member's account ID.
             */
            userId: string;
            /** @description The member's email address. */
            email: string;
            /** @description Owner, Admin or Broadcaster. */
            role: components["schemas"]["MembershipRole"];
            /**
             * Format: date-time
             * @description When the member joined.
             */
            joinedAt: string;
        };
        MembershipResponse: {
            /** Format: uuid */
            tenantId: string;
            tenantName: string;
            tenantSlug: string;
            role: components["schemas"]["MembershipRole"];
        };
        /** @enum {unknown} */
        MembershipRole: "Owner" | "Admin" | "Broadcaster";
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            memberships: components["schemas"]["MembershipResponse"][];
        };
        /** @description A station the signed-in user can broadcast to. */
        MyStationResponse: {
            /**
             * Format: uuid
             * @description Send it as `X-Tenant-Id` when asking for the broadcast target.
             */
            tenantId: string;
            /** @description The station's tenant. */
            tenantName: string;
            /**
             * Format: uuid
             * @description Station ID in the API.
             */
            stationId: string;
            /** @description Station ID in mounts and listener URLs. */
            publicId: string;
            /** @description Station name. */
            name: string;
            /** @description The user's role in the tenant. */
            role: components["schemas"]["MembershipRole"];
        };
        /** @description One page of results. */
        PagedListOfStationResponse: {
            /** @description The items on this page. */
            items: components["schemas"]["StationResponse"][];
            /**
             * Format: int32
             * @description 1-based page number.
             */
            page: number | string;
            /**
             * Format: int32
             * @description Items per page (1-100).
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description Items on all pages.
             */
            totalCount: number | string;
        };
        /** @description A plan's limits and features. */
        PlanResponse: {
            /** @description Plan ID, e.g. "starter". */
            id: string;
            /** @description Display name. */
            name: string;
            /**
             * Format: int32
             * @description Stations the tenant may have.
             */
            maxStations: number | string;
            /**
             * Format: int32
             * @description Concurrent listeners per station.
             */
            maxListeners: number | string;
            /**
             * Format: int32
             * @description Highest stream bitrate accepted.
             */
            maxBitrateKbps: number | string;
            /** @description Stream formats: "mp3", "opus". */
            formats: string[];
            /** @description RadioBrowser listing allowed. */
            directoryListing: boolean;
            /** @description Embeddable player allowed. */
            embed: boolean;
            /** @description Listener statistics included. */
            analytics: boolean;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        ResetPasswordRequest: {
            email: string;
            code: string;
            newPassword: string;
        };
        /**
         * @description A station.
         * @example {
         *       "id": "01927f5e-6c1a-7b3e-9a52-3f1d2c4b5a69",
         *       "publicId": "k3m9x2p7qa",
         *       "name": "Radio Mada",
         *       "slug": "radio-mada",
         *       "description": "News and salegy from Antananarivo",
         *       "genre": "Talk",
         *       "country": "MG",
         *       "language": "mg",
         *       "logoUrl": null,
         *       "website": "https://radiomada.example",
         *       "listInDirectory": true,
         *       "createdAt": "2026-10-09T12:00:00+00:00",
         *       "listenerUrls": {
         *         "mp3": "https://listen.tropicastradio.com/stations/k3m9x2p7qa/live.mp3",
         *         "opus": "https://listen.tropicastradio.com/stations/k3m9x2p7qa/live.opus"
         *       }
         *     }
         */
        StationResponse: {
            /**
             * Format: uuid
             * @description ID in the API.
             */
            id: string;
            /** @description ID in listener URLs and Icecast mounts; never changes. */
            publicId: string;
            /** @description Display name. */
            name: string;
            /** @description URL name, unique in the tenant. */
            slug: string;
            /** @description Shown on the public page and in directories. */
            description: string;
            /** @description Music or programme genre. */
            genre: string;
            /** @description ISO 3166-1 alpha-2 code. */
            country: null | string;
            /** @description BCP 47 language tag. */
            language: null | string;
            /**
             * Format: uri
             * @description Logo address.
             */
            logoUrl: null | string;
            /**
             * Format: uri
             * @description The station's website.
             */
            website: null | string;
            /** @description Listed on RadioBrowser (only when the plan includes it). */
            listInDirectory: boolean;
            /**
             * Format: date-time
             * @description When the station was created.
             */
            createdAt: string;
            /** @description Where listeners play the station. */
            listenerUrls: components["schemas"]["ListenerUrls"];
        };
        /** @description A streaming node's provisioning state. */
        StreamingNodeResponse: {
            /** @description Node name. */
            node: string;
            /** @description The node runs the desired station limits. */
            inSync: boolean;
            /** @description Version of the limits the database asks for. */
            desiredVersion: null | string;
            /** @description Version last applied to the node. */
            appliedVersion: null | string;
            /**
             * Format: date-time
             * @description When it was applied.
             */
            appliedAt: null | string;
            /**
             * Format: date-time
             * @description Last apply attempt.
             */
            lastAttemptAt: null | string;
            /**
             * Format: int32
             * @description Failures since the last success.
             */
            failedAttempts: number | string;
            /**
             * Format: date-time
             * @description Next retry after a failure.
             */
            nextAttemptAt: null | string;
            /** @description Last failure. */
            lastError: null | string;
        };
        /** @description A tenant (customer account). */
        TenantResponse: {
            /**
             * Format: uuid
             * @description Tenant ID; send it as X-Tenant-Id to choose this tenant.
             */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description URL name, unique across Tropicast. */
            slug: string;
            /** @description Active or Suspended. */
            status: components["schemas"]["TenantStatus"];
            /** @description Current plan. */
            plan: components["schemas"]["PlanResponse"];
            /**
             * Format: int32
             * @description Stations in use, out of Plan.MaxStations.
             */
            stationCount: number | string;
        };
        /** @enum {unknown} */
        TenantStatus: "Active" | "Suspended";
        TokenRequest: {
            email: string;
            password: string;
            deviceName: string;
        };
        /** @description Tokens for the desktop app: string TokenResponse.AccessToken lasts 15 minutes; refresh to get a new pair. */
        TokenResponse: {
            /** @description Always `Bearer`. */
            tokenType: string;
            /** @description Send as `Authorization: Bearer …`. */
            accessToken: string;
            /**
             * Format: int64
             * @description Access token lifetime in seconds.
             */
            expiresIn: number | string;
            /** @description One-time: each refresh returns a new one. Revoke it to sign the device out. */
            refreshToken: string;
        };
        /**
         * @description Changes station settings; omitted (null) fields keep their value.
         * @example {
         *       "genre": "Salegy",
         *       "description": "Music all night"
         *     }
         */
        UpdateStationCommand: {
            name?: null | string;
            slug?: null | string;
            description?: null | string;
            genre?: null | string;
            country?: null | string;
            language?: null | string;
            /** Format: uri */
            logoUrl?: null | string;
            /** Format: uri */
            website?: null | string;
            listInDirectory?: null | boolean;
        };
        /**
         * @description Changes the tenant's name or slug; omitted fields keep their value.
         * @example {
         *       "name": "Radio Mada Media"
         *     }
         */
        UpdateTenantCommand: {
            name?: null | string;
            slug?: null | string;
        };
        UserCodeRequest: {
            userCode: string;
        };
        /** @description API version information. */
        VersionInfo: {
            /** @description Semantic version of the API build. */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
}
