// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tropicast.Dashboard.Infrastructure.Persistence;

#nullable disable

namespace Tropicast.Dashboard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009201434_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Plans.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<bool>("Analytics")
                        .HasColumnType("boolean")
                        .HasColumnName("analytics");

                    b.Property<bool>("DirectoryListing")
                        .HasColumnType("boolean")
                        .HasColumnName("directory_listing");

                    b.Property<bool>("Embed")
                        .HasColumnType("boolean")
                        .HasColumnName("embed");

                    b.Property<string>("Formats")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formats");

                    b.Property<int>("MaxBitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("max_bitrate_kbps");

                    b.Property<int>("MaxListeners")
                        .HasColumnType("integer")
                        .HasColumnName("max_listeners");

                    b.Property<int>("MaxStations")
                        .HasColumnType("integer")
                        .HasColumnName("max_stations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.ToTable("plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "free",
                            Analytics = true,
                            DirectoryListing = false,
                            Embed = false,
                            Formats = "Mp3, Opus",
                            MaxBitrateKbps = 64,
                            MaxListeners = 100,
                            MaxStations = 1,
                            Name = "Free",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "starter",
                            Analytics = true,
                            DirectoryListing = true,
                            Embed = false,
                            Formats = "Mp3, Opus",
                            MaxBitrateKbps = 128,
                            MaxListeners = 500,
                            MaxStations = 1,
                            Name = "Starter",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "growth",
                            Analytics = true,
                            DirectoryListing = true,
                            Embed = true,
                            Formats = "Mp3, Opus",
                            MaxBitrateKbps = 192,
                            MaxListeners = 5000,
                            MaxStations = 3,
                            Name = "Growth",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "pro",
                            Analytics = true,
                            DirectoryListing = true,
                            Embed = true,
                            Formats = "Mp3, Opus",
                            MaxBitrateKbps = 320,
                            MaxListeners = 25000,
                            MaxStations = 5,
                            Name = "Pro",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Plans.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan_id");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("ProviderSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_provider_subscription_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subscriptions_tenant_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.BroadcastCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_broadcast_credentials");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_broadcast_credentials_station_id");

                    b.ToTable("broadcast_credentials", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.LiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_live_sessions");

                    b.HasIndex("StationId", "Format")
                        .IsUnique()
                        .HasDatabaseName("ix_live_sessions_station_id_format")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("StationId", "StartedAt")
                        .HasDatabaseName("ix_live_sessions_station_id_started_at");

                    b.ToTable("live_sessions", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("genre");

                    b.Property<string>("Language")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language");

                    b.Property<bool>("ListInDirectory")
                        .HasColumnType("boolean")
                        .HasColumnName("list_in_directory");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("public_id")
                        .IsFixedLength();

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_public_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_stations_tenant_id_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.StationStatsRollup", b =>
                {
                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<string>("Interval")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<long>("EgressBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("egress_bytes");

                    b.Property<double>("ListenerHours")
                        .HasColumnType("double precision")
                        .HasColumnName("listener_hours");

                    b.Property<int>("PeakListeners")
                        .HasColumnType("integer")
                        .HasColumnName("peak_listeners");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("StationId", "Interval", "PeriodStart")
                        .HasName("pk_station_stats_rollups");

                    b.ToTable("station_stats_rollups", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.StreamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("MountBase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mount_base");

                    b.Property<string>("Node")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("node");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stream_assignments");

                    b.HasIndex("StationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stream_assignments_station_id");

                    b.ToTable("stream_assignments", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Tenants.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memberships_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_tenant_id_user_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_tenants_plan_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Plans.Subscription", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan_id");

                    b.HasOne("Tropicast.Dashboard.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_tenants_tenant_id");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.BroadcastCredential", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Stations.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broadcast_credentials_stations_station_id");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.LiveSession", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Stations.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_live_sessions_stations_station_id");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.Station", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stations_tenants_tenant_id");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.StationStatsRollup", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Stations.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_station_stats_rollups_stations_station_id");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Stations.StreamAssignment", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Stations.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stream_assignments_stations_station_id");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Tenants.Membership", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_tenants_tenant_id");
                });

            modelBuilder.Entity("Tropicast.Dashboard.Domain.Tenants.Tenant", b =>
                {
                    b.HasOne("Tropicast.Dashboard.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenants_plans_plan_id");
                });
#pragma warning restore 612, 618
        }
    }
}
